logging:
  enabled: false

fluentbit:
  kind: DaemonSet

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  config:
    service: |
      [SERVICE]
          Flush        1
          Daemon       Off
          Log_Level    info
          Parsers_File parsers.conf
          HTTP_Server  On
          HTTP_Listen  ::
          HTTP_Port    2020
          Health_Check On

    inputs: |
      [INPUT]
          Name             tail
          Path             /var/log/containers/*.log
          multiline.parser docker,cri
          Tag              kube.*
          Refresh_Interval 5
          Rotate_Wait      30
          Mem_Buf_Limit    5MB
          Skip_Long_Lines  On
          DB               /var/log/flb_kube.db
          Ignore_Older     4h

      [INPUT]
          Name            systemd
          Tag             host.*
          Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail  On

    filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          K8S-Logging.Parser  On
          K8S-Logging.Exclude Off
          Keep_Log            On
          Merge_Log           On

    outputs: |
      [OUTPUT]
          Name              loki
          Match             kube.*
          Host              internal-observability-internal-alb-213137362.ap-south-1.elb.amazonaws.com
          Port              80
          Drop_Single_Key   On
          Labels            cluster=alcs-saas-eks-ap-south-1-dev,namespace=$kubernetes['namespace_name'],container=$kubernetes['container_name'],deployment=$kubernetes['labels']['app.kubernetes.io/name'],service_name=$kubernetes['labels']['app'],application_group=$kubernetes['labels']['rems/application_group'],rems_service=$kubernetes['labels']['rems/service']
          Remove_Keys       kubernetes

      [OUTPUT]
          Name              loki
          Match             host.*
          Host              internal-observability-internal-alb-213137362.ap-south-1.elb.amazonaws.com
          Port              80
          Labels            cluster=alcs-saas-eks-ap-south-1-dev,job=kubelet
